# Generated by Django 4.1.3 on 2022-11-05 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50, null=True)),
                ("country", models.CharField(max_length=5, null=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("description", models.CharField(max_length=100, null=True)),
                ("humidity", models.SmallIntegerField(null=True)),
                ("temperature", models.FloatField(null=True)),
                ("favourite", models.BooleanField(default=False)),
            ],
        ),
    ]
